version: 2.1

jobs:
  test-lighthouse:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: oddsite-{{ checksum ".pnp.js" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Lighthouse Testing
          command: yarn test:performance

  build:
    working_directory: ~/oddsite
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: oddsite-{{ checksum ".pnp.js" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable --immutable-cache
      - persist_to_workspace:
          root: .
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz
      - save_cache:
          key: oddsite-{{ checksum ".pnp.js" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz

  lint:
    working_directory: ~/oddsite
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test:
    working_directory: ~/oddsite
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
      - run:
          name: Test JS
          command: yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: './coverage'
      - store_artifacts:
          path: coverage
          destination: js-test-reports
      - store_test_results:
          path: coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - test-lighthouse:
          requires:
            - build
